/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_derongliu_ndk_NDKTest */

#ifndef _Included_com_example_derongliu_ndk_NDKTest
#define _Included_com_example_derongliu_ndk_NDKTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_derongliu_ndk_NDKTest
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_derongliu_ndk_NDKTest_sayHello
  (JNIEnv *, jobject);

/*
 * Class:     com_example_derongliu_ndk_NDKTest
 * Method:    sayHelloObject
 * Signature: (Lcom/example/derongliu/ndk/Person;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_derongliu_ndk_NDKTest_sayHelloObject
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_example_derongliu_ndk_NDKTest
 * Method:    getPerson
 * Signature: ()Lcom/example/derongliu/ndk/Person;
 */
JNIEXPORT jobject JNICALL Java_com_example_derongliu_ndk_NDKTest_getPerson
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
